import pandas as pd

cols = [
    'QUESTID2',
    'AGE2',
    'BOOKED',
    'MOVSINPYR2',
    'PDEN10',
    'COUTYP4',
    'YESTSCIG',
    'YESTSMJ',
    'YESTSALC',
    'YESTSDNK',
    'YEYFGTSW',
    'YEYFGTGP',
    'YESCHACT',
    'YECOMACT',
    'YEFAIACT',
    'YEOTHACT',
    'YEATNDYR',
    'YESCHFLT',
    'YESCHWRK',
    'YESCHIMP',
    'YESCHINT',
    'YETCGJOB',
    'YELSTGRD',
    'YEPCHKHW',
    'YEPHLPHW',
    'YEPCHORE',
    'YEPLMTTV',
    'YEPLMTSN',
    'YEPGDJOB',
    'YEPPROUD',
    'YEYARGUP',
    'YEPPKCIG',
    'YEPMJEVR',
    'YEPMJMO',
    'YEPALDLY',
    'YEPRTDNG',
    'YEGPKCIG',
    'YEGMJEVR',
    'YEGMJMO',
    'YEGALDLY',
    'YEFPKCIG',
    'YEFMJEVR',
    'YEFMJMO',
    'YEFALDLY',
    'YERLGSVC',
    'YERLGIMP',
    'YERLDCSN',
    'YERLFRND',
    'YODPREV',
    'YODSCEV',
    'YOLOSEV',
    'YOWRHRS',
    'YOWRDST',
    'YOWRCHR',
    'YOWRIMP',
    'YODPPROB',
    'HEALTH',
    'DIFFTHINK',
    'YEPRBSLV',
    'YEVIOPRV',
    'YEDGPRGP',
    'YEDECLAS',
    'YEDERGLR',
    'YEDESPCL',
    'YEPVNTYR',
    'CIGEVER',
    'SMKLSSEVR',
    'CIGAREVR',
    'PIPEVER',
    'ALCEVER',
    'MJEVER',
    'COCEVER',
    'CRKEVER',
    'HEREVER',
    'HALLUCEVR',
    'INHALEVER',
    'METHAMEVR',
    'PNRANYLIF',
    'TRQANYLIF',
    'STMANYLIF',
    'SEDANYLIF',
    'PNRNMLIF',
    'COLDMEDS'
]

path = r'../data/NSDUH_2019.SAV'

def youth_df():
    df = pd.read_spss(path, usecols = cols)
    df = df.loc[df['AGE2'].isin([1, 2, 3, 4, 5, 6])]
    return df
